[project]
name = "lox-python"
version = "0.1.0"
description = "Python version of the Lox interpreter from the book 'Crafting Interpreters' by Bob Nystrom"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.5",
]
